### ISSUE TITLE
Docs don't render nicely

### ISSUE THREAD

**Issue by danielhomola** [tonybaloney/sphinxcontrib-confluencebuilder#107]
Thanks a lot for this package! I managed to build the docs and upload them automatically to our confluence page, but they render horribly.. I don't know if this is how they're supposed to look like but they are full with awkward charters and parts like:

:Parameters:
\*\*function.name\*\*
\*\*argument_name (___)\*\*

We use google style docstrings which render perfectly fine with sphinx into beautiful HTML pages, but once they are upload to confluence they are pretty much undreadable.. 

Am I missing some package or setting here?

Many thanks for any suggestions in advance!

**Comment by jdknight** [comment]
I'm assuming you are talking about rendering AutoDoc content (if not, I'd be curious to know what addition Sphinx extensions you are using). I believe this is being discussed in #51. The current plan is to improve documentation-related rendering/publishing in [milestone 0.10](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/4). There is currently an active release about to happen (milestone 0.9) which should wrap-up soon (ideally, within a week or so; see #95). This release _may_ have slightly improved visuals for AutoDoc content, but nothing officially tested. Hopefully we'll be able to look at this soon.

**Comment by danielhomola** [comment]
Thanks a lot for your reply. Yes it's autodoc generated content. I'll check back later for 0.9 and see if things are better. Thanks again!

**Comment by jdknight** [comment]
Marking as duplicate and closing. If any additional comments would like to be made, please use issue #107 instead. Thanks.
