### ISSUE TITLE
glossary support - or not?

### ISSUE THREAD

**Issue by papadeltasierra** [tonybaloney/sphinxcontrib-confluencebuilder#108]
The main 'README' does not list 'glossary' as a supported mark-up but there is a 'doc' page that does - so is it supported?  I ask because I'm getting warnings like this:
WARNING: unable to build link to document due to missing target (in config): term-federation
implying that my glossary entry for 'federation' is not working (it does for HTML).

**Comment by jdknight** [comment]
Confirming that while the creation of a glossary provides formatted output, glossary terms do not yet generate an appropriate header/anchor to link to (which in turn a term link, ex. `` :term:`Sphinx` ``, would generate an error "unable to build link to document"; as reported).

**Comment by papadeltasierra** [comment]
I think I have a fix for this - is the usual process to fork and request a pull? My solution adds the missing anchor for the :term:`term-Sphinx` and makes the format of the 'term' and the 'description' configurable (I don't like the existing 'bg.' default ;-).  I'll leave the defaults as they are but allow them to be configurable.

**Comment by jdknight** [comment]
Contributions are welcome (if they are sane). We've yet to make a proper `CONTRIBUTING` file. 😅

I'd consult #97 for a recent new contributor discussion. It is required (well, required if you want my +1) to [sign your commits](https://www.kernel.org/doc/html/v4.12/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin).

**Comment by jdknight** [comment]
(tracking: #112)

**Comment by papadeltasierra** [comment]
James,

Just checking that you are not waiting for anything more from me – is there a ‘button’ that I’m supposed to push to indicate that I’ve finished making changes?

Regards,
Paul DS.

**Comment by jdknight** [comment]
@papadeltasierra, nope. I usually focus on a day between Thursday-Saturday for this extension, so hopefully I'll be able to get to your PR's then. Thanks for the quick turn around; sorry about the slow process.

**Comment by papadeltasierra** [comment]
No problem – I’ll note your schedule.  I’ve not used the ‘Pull Request’ system before so was just afraid I’d missed a step somewhere.

**Comment by jdknight** [comment]
Glossary references are now supported (thanks @papadeltasierra; see #112). This fix will be available in a v0.10 release. I'll be closing this issue as the specific problem brought up in this issue has been addressed.
