### ISSUE TITLE
Can't update pages on confluence cloud 

### ISSUE THREAD

**Issue by Oloremo** [tonybaloney/sphinxcontrib-confluencebuilder#118]
Hi,

Version: sphinxcontrib-confluencebuilder (0.9)

Page creation works just fine, but then I try to update the page I receive the:

```
Traceback (most recent call last):
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 406, in build
    self.finish()
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 356, in finish
    self.publish_doc(docname, output)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 310, in publish_doc
    uploaded_id = self.publisher.storePage(title, output, parent_id)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 357, in storePage
    self.rest_client.put('content', page['id'], updatePage)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/rest.py", line 170, in put
    raise ConfluenceBadApiError(errdata)
ConfluenceBadApiError: ---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://SECRET.atlassian.net/wiki/rest/api
API: content
MSG: Could not update Content of type : class com.atlassian.confluence.pages.Page with id 448200776
{
  "body": {
    "storage": {
      "representation": "storage",
      "value": "<ul>\n\t<li><ac:link><ri:page ri:content-title=\"Quick Start\" /></ac:link></li>\n</ul>\n\n\n<h2>Summary</h2>\n\n<p>This document describes all things Ansible.</p>\n\n<ac:structured-macro ac:name=\"warning\" ac:schema-version=\"1\" ac:macro-id=\"8ce74698-6ef3-4e57-aec7-f5630db78d74\"><ac:rich-text-body><p>This doc is auto&#45;generated from the following sources: <a href=\"SECRET\">SECRET</a></p></ac:rich-text-body></ac:structured-macro>"
    }
  },
  "ancestors": [
    {
      "id": "448299149"
    }
  ],
  "space": {
    "key": "Devops"
  },
  "title": "Ansible docs",
  "version": {
    "number": 2
  },
  "type": "page",
  "id": "448200776"
}
```

How to reproduce:
Post same doc twice. 
```
sphinx-build -v -T -D confluence_server_pass=SECRET -b confluence . _build/confluence -E -a
sphinx-build -v -T -D confluence_server_pass=SECRET -b confluence . _build/confluence -E -a
```

**Comment by jdknight** [comment]
Interesting -- this issue was observed in the past (see #65) but the root cause never found. Trying to reproduce this issue with the following tests does not appear to reveal anything:
- Version 0.9 (sphinxcontrib-confluencebuilder);
- Confluence Cloud (test space and personal space); and
- Validation results and new `sphinx-quickstart` set.

Inspecting the output from the original [ConfluenceBadApiError event](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/issues/118#issue-341114983), the data seems to be correct. Proper storage content, titles, identifiers appear to be valid and version values appear to be valid.

Taking a look at Confluence's server sources (which most likely vary from Atlassian Cloud service's sources), there appears to be a couple of cases where I can see the error `Could not update Content of type` being generated (which the API does not explicit mention in the result):

- Are you sure you user as `Edit` permissions for the page/space? It could be that the authentication session configured for the publish event can create pages but cannot update existing pages (`PageContentTypeApiSupport` check).
- (assuming this is not the case) From the JSON response, it appears you are using `confluence_parent_page` (and maybe `confluence_parent_page_id_check`; due to the existence of the `ancestors` entry). There exists a check (`ContentCreator` check) which would throw an error if the provided parent page's space is not the same as the updating page. I assume this is not the case since I doubt pages are being moved/changed between the two calls (but figured I'd mention it just in case).
- Do you know if your Confluence Cloud instance uses any content-policy/special Marketplace add-ons? It could be that an add-on may be restricting a page update (`DefaultContentRestrictionServiceValidator` check).

**Comment by Oloremo** [comment]
> Are you sure you user as Edit permissions for the page/space?

Yes, I did try to give this user all available permission just for the sake of the test without any success.

> From the JSON response, it appears you are using confluence_parent_page
This is my configuration:
```
confluence_publish = True
confluence_server_url = 'https://kinda-secret.atlassian.net/wiki/'
confluence_space_name = 'Devops'
confluence_parent_page = 'Ansible'
confluence_disable_autogen_title = True
confluence_server_user = 'jenkins@kinda-secret.com'
confluence_server_pass = 'SECRET'
```

>  I assume this is not the case since I doubt pages are being moved/changed between the two calls
Yeah, it's not the case. 

> Do you know if your Confluence Cloud instance uses any content-policy/special Marketplace add-ons? It could be that an add-on may be restricting a page update 

We have Google Auth enabled, besides that there is nothing in particular.

**Comment by jdknight** [comment]
Looking at [Confluence's REST API for "Update content"](https://developer.atlassian.com/cloud/confluence/rest/#api-content-id-put), it indicates that a `400 Bad Request` (which appears to be what you're experiencing) is a result of either of the following:

1. The request body is missing required parameters (version, type, title).
2. The type property has been set incorrectly.

From the latter, we can see that the `type` property appears to be properly set (to `page`; a valid entry as mentioned in the documentation). The first condition indicates that an issue occurs if an issue missing a required parameter. For `version`, the value exists and it makes sense that it is a valid value with `2` (the update/next version). We've already discussed `type`. The last required parameter is `title`. I'm wondering if somehow the title value is resulting in a possible error. Seeing that your example shows an explicit title value of `Ansible docs`, I do not see what it is an issue (no odd or unescaped characters).

Are there any other Sphinx/extension warnings generated above the observed exception (specifically having to mention about conflicting page titles)?

The only other option I can think of off hand is to attempt to publish using XML-RPC API (via `confluence_disable_rest = True`). Maybe Confluence will provide an alternative error message in he XML-RPC API result.

**Comment by Oloremo** [comment]
So what I tried:

1) Setting confluence_disable_rest = True
After that, I was unable to authenticate via my token in confluence.

2) Removing the `confluence_parent_page`
The same result as with it - creation works and update doesn't

3) Simplify the document
Right now it looks like this:

```
Ansible
=======

.. toctree::
   :maxdepth: 2
   :caption: Contents:

```

> Are there any other Sphinx/extension warnings generated above the observed exception (specifically having to mention about conflicting page titles)?

Whole output of 2 commands:

```
(tools) iHAL9000:source oloremo$ sphinx-build -v -T -D confluence_server_pass=SECRET  -b confluence . _build/confluence -E -a
Running Sphinx v1.7.5
building [mo]: all of 0 po files
building [confluence]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... mapping index to title: Ansible
track index toc-depth: 2
mapping index#ansible to target: Ansible
done
writing output... [100%] index

tracking docname index's upload id: 483426456

build succeeded.
(tools) iHAL9000:source oloremo$ sphinx-build -v -T -D confluence_server_pass=SECRET -b confluence . _build/confluence -E -a
Running Sphinx v1.7.5
building [mo]: all of 0 po files
building [confluence]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... mapping index to title: Ansible
track index toc-depth: 2
mapping index#ansible to target: Ansible
done
writing output... [100%] index

publishing... [100%] index
Traceback (most recent call last):
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 406, in build
    self.finish()
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 356, in finish
    self.publish_doc(docname, output)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 310, in publish_doc
    uploaded_id = self.publisher.storePage(title, output, parent_id)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 357, in storePage
    self.rest_client.put('content', page['id'], updatePage)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/rest.py", line 170, in put
    raise ConfluenceBadApiError(errdata)
ConfluenceBadApiError: ---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://kinda-secret.atlassian.net/wiki/rest/api
API: content
MSG: Could not update Content of type : class com.atlassian.confluence.pages.Page with id 483426456
{
  "body": {
    "storage": {
      "representation": "storage",
      "value": "<h1>Indices and tables</h1>\n\n<ul>\n\t<li></li>\n\t<li></li>\n\t<li></li>\n</ul>\n"
    }
  },
  "space": {
    "key": "Devops"
  },
  "title": "Ansible",
  "version": {
    "number": 2
  },
  "type": "page",
  "id": "483426456"
}
---


sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://kinda-secret.atlassian.net/wiki/rest/api
API: content
MSG: Could not update Content of type : class com.atlassian.confluence.pages.Page with id 483426456
{
  "body": {
    "storage": {
      "representation": "storage",
      "value": "<h1>Indices and tables</h1>\n\n<ul>\n\t<li></li>\n\t<li></li>\n\t<li></li>\n</ul>\n"
    }
  },
  "space": {
    "key": "Devops"
  },
  "title": "Ansible",
  "version": {
    "number": 2
  },
  "type": "page",
  "id": "483426456"
}
---

```

**Comment by jdknight** [comment]
@Oloremo, unfortunately, I do not have any solution at this time for you. I have tried a series of additional steps on two other machines without being able to reproduce your issue. My environment includes:

**[conf.py]**
```
# -*- coding: utf-8 -*-

extensions = ['sphinxcontrib.confluencebuilder']

confluence_parent_page = 'container'
confluence_publish = True
confluence_server_pass='OMITTED'
confluence_server_url='https://jdknight.atlassian.net/wiki/'
confluence_server_user='james.d.knight@live.com'
confluence_space_name = 'OMITTED'
```
**[content.rst]**
```
Ansible
=======

.. toctree::
   :maxdepth: 2
   :caption: Contents:

content
```
**[cmd]**
```
python -m sphinx -v -T -D confluence_server_pass=OMITTED -b confluence . _build/confluence -E -a
```
Yet, invoking the above command multiple times always yields with a successful page update. Do you think I am missing anything?

------

I noticed in your example the following content for the `body`'s `value` entry:
```
<h1>Indices and tables</h1>\n\n<ul>\n\t<li></li>\n\t<li></li>\n\t<li></li>\n</ul>\n
```
Is this an exact example of what you see when the error you are experiencing occurs (I see a series of empty list items)? I'm suspecting you may be filtering some of your content, which is fine, but it may hint to why I am unable to observe the issue locally (could be an odd character, unescaped content or other encoding issues). If I can just get a confirmation that have or have not filtered out content from the `title` or `value`, it could help point me where to look.

Still, it is odd that the creation of the page with content is successful and the update of a page is not. I recall seeing a Confluence issue in the past where a page's content would get corrupted after updating with Unicode content. While I would expect those issues to be resolved now (especially on a Confluence Cloud instance), I am fishing for anything now.

With respect to `confluence_disable_rest` configuration option; yes, you will be unable to authentication with the Confluence instance using an API token. The pipe (by Atlassian design) only supports an authenticated user account's username and password. If your test environment prevents you from using your user's password, no worries; however, if it is not an issue for you, it could be helpful to see the output result from an XML-RPC request (for a page update).

Also, what version of `requests` are you using (`python -m pip show requests`)? I wonder if there's an issue related to a put event and encoding (long shot).

**Comment by Oloremo** [comment]
Hey, thanks for looking into this issue for me, really appreciate it.

>  I'm suspecting you may be filtering some of your content

I didn't
The only thing I redacted is the API key and company url name.

Right now I use this file for tests:
```
$ cat index.rst
Ansible
=======

TEST
```

> Also, what version of requests are you using

Version: 2.19.1

> you could try a more recent development branch. The branch feature/storage-format-conversion

Did try... the same result.

I'll try to look into the XML-RPC approach

**Comment by jdknight** [comment]
@Oloremo... well, I just found out that a REST failure can have more information about the error outside the currently parsed JSON response (😓).

There is two approaches you can try to help us get a more explicit error:

1. You can try to invoke a manual CURL request matching your content (replacing `YOUR_USERNAME` and `YOUR_SITE` to your respective configuration):
```
curl -X 'PUT' --user 'YOUR_USERNAME' -H 'Content-Type: application/json' -d '{"body": {"storage": {"representation": "storage", "value": "<p>TEST</p>"}}, "space": {"key": "Devops"}, "title": "Ansible", "type": "page", "version": {"number": 2}, "id": "483426456"}' 'https://YOUR_SITE.atlassian.net/wiki/rest/api/content/483426456'
```
On error, you should see the a couple of locations to extract the real error; otherwise you will see a lot of JSON information (on success).

2. You can manually edit your local `sphinxcontrib-confluencebuilder` sources and modify the following line (in `_format_error`; at bottom):
```
err += 'MSG: {}'.format(rsp.json()['message'])
```
to:
```
err += 'DATA: {}'.format(json.dumps(rsp.json(), indent=2))
```

(file: `/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/rest.py`)

This should dump a more in-depth error message to the console on error.

----

In the meantime, I will queue up another fix for this extension so that it always displays the entire JSON dump of a failed request.

**Comment by Oloremo** [comment]
Hey, thanks for the branch, it makes it a bit easier indeed.

Looks like your idea is working and there is a way more specific error!

```
Running Sphinx v1.7.6
building [mo]: all of 0 po files
building [confluence]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... mapping index to title: Ansible
mapping index#ansible to target: Ansible
done
writing output... [100%] index

publishing... [100%] index
Traceback (most recent call last):
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 406, in build
    self.finish()
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 356, in finish
    self.publish_doc(docname, output)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 310, in publish_doc
    uploaded_id = self.publisher.storePage(title, output, parent_id)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 357, in storePage
    self.rest_client.put('content', page['id'], updatePage)
  File "/Users/oloremo/git/tools/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/rest.py", line 170, in put
    raise ConfluenceBadApiError(errdata)
ConfluenceBadApiError: ---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://OMITED.atlassian.net/wiki/rest/api
API: content
DATA: {
  "message": "Could not update Content of type : class com.atlassian.confluence.pages.Page with id 496337007",
  "data": {
    "successful": false,
    "errors": [
      {
        "message": {
          "args": [],
          "key": "You can't change an existing page's space."
        }
      }
    ],
    "valid": false,
    "authorized": true
  },
  "statusCode": 400
}
{
  "body": {
    "storage": {
      "representation": "storage",
      "value": "<p>TEST</p>"
    }
  },
  "space": {
    "key": "Devops"
  },
  "title": "Ansible",
  "version": {
    "number": 2
  },
  "type": "page",
  "id": "496337007"
}
---


sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://OMITED.atlassian.net/wiki/rest/api
API: content
DATA: {
  "message": "Could not update Content of type : class com.atlassian.confluence.pages.Page with id 496337007",
  "data": {
    "successful": false,
    "errors": [
      {
        "message": {
          "args": [],
          "key": "You can't change an existing page's space."
        }
      }
    ],
    "valid": false,
    "authorized": true
  },
  "statusCode": 400
}
{
  "body": {
    "storage": {
      "representation": "storage",
      "value": "<p>TEST</p>"
    }
  },
  "space": {
    "key": "Devops"
  },
  "title": "Ansible",
  "version": {
    "number": 2
  },
  "type": "page",
  "id": "496337007"
}
---
```

> You can't change an existing page's space.

But... I don't change the page space.

**Comment by jdknight** [comment]
Neat.

I assume with the API endpoint, the space `key` value and the page `id` value, this would be a "unique identifier" in Confluence's eyes. I wonder why Confluence thinks the space value has changed.

We can check to see how Confluence really interprets the page identifier you are trying to update, by using the following command (replacing `YOUR_USERNAME` and `YOUR_SITE` to your respective configuration):
```
curl -u 'YOUR_USERNAME' -G "https://YOUR_SITE.atlassian.net/wiki/rest/api/content/search" --data-urlencode "cql=(type=page and space='Devops' and id=496337007)"
```
I would expect that you should see a `"size":1` entry. If you do not, that would be an issue.

Another sanity check is examining the value of `space` in the result set. The value should be set to `"space":"/rest/api/space/Devops"`. If it is not, that would be an issue.

If the above checks appear fine, you could also try running the above curl request with the following CQL adjustments:

- `type=page and id=496337007`
- `id=496337007`

While these queries could produce multiple results, seeing them only provide a single result count would alleviate some doubt related to the `space` field in the CQL search.

**Comment by Oloremo** [comment]
> We can check to see how Confluence really interprets the page identifier you are trying to update, by using the following command (replacing YOUR_USERNAME and YOUR_SITE to your respective configuration):

So:
1) size: 1 == OK
2) "space": "/rest/api/space/devops" == lowercase...

Setting it to the lowercase in the config fixed the issue.

I'm feeling really stupid now, but Atlassian acting strange too, why on earth you allow to create the page like this and not update?

So anyway thank you for this debugging session and your time!

**Comment by jdknight** [comment]
@Oloremo, wow -- all that just for a single casing issue. 😛 

I see that there is an issue at Atlassian's issue tracker mentioning the issue (see [CONFSERVER-40303](https://jira.atlassian.com/browse/CONFSERVER-40303)). Inspecting Confluence Server sources, I think I see where the issue exists -- in the page creation attempt it compares the space name with `equalsIgnoreCase` where everywhere else in the code it checks with `equals`. I have updated their ticket with more information.

Thanks for trying things out during this investigation. At least from this incident, this extension has a prospect improvement on dealing with future REST errors. I am happy since I suspect this was the issue also observed in #65 (which a solution was never found).

I'll make a note to update documentation to reflect the space name (and parent page name) are case-sensitive values.
