### ISSUE TITLE
JIRA directive

### ISSUE THREAD

**Issue by cstarner** [tonybaloney/sphinxcontrib-confluencebuilder#143]
I was wondering if anyone would be interested in a JIRA directive for this library. It would essentially function as wrapper for the <code>jira</code> macro in Confluence. Outside of possible needing to specify a specific JIRA server as an argument to the macro (which appears to be optional), I don't believe it would add substantially to required configuration.

I would be more than happy to work on this myself, and submit it as a pull request; I'm just attempting to gauge community interest

**Comment by meltingturret** [comment]
Of cause 😎

**Comment by jdknight** [comment]
@cstarner, I would be glad to help provide support to review/integrate possible enhancements to this extension. Personally, I always felt that this extension's primary goal is to help translate reStructuredText, Sphinx markup and common Sphinx extension markup into Confluence-supported content -- not specifically adding new directive/role types. That being said, I do not see why it would be a major issue to try to support JIRA markup (let alone other macros to integrate other Atlassian-based products). I would be curious to know @tonybaloney's thoughts on the matter.

Some initial comments on this prospect work:

- Support required for all versions Atlassian supports (Cloud and [various server versions][1]).
- It is recommended, if possible, any testing you perform can handle zero to many connected JIRA instances to a Confluence instance.
- Respect `confluence_adv_restricted_macros` (for example, see `can_admonition` inside the translator).
- Reminder to check out [CONTRIBUTING.rst][2].

[1]: https://confluence.atlassian.com/support/atlassian-support-end-of-life-policy-201851003.html
[2]: https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/master/CONTRIBUTING.rst

**Comment by cstarner** [comment]
@jdknight Thank you for the response, and the offer to help. I will get started on getting this working. 


- I have access to a Cloud version, and can get my hands on a server version as well. Near as I can tell, the syntax is the same, but I will confirm this.
- JIRA macros in Confluence require the specification of a JIRA server name and ID, which may well handle most of the second point for us. I will try sending bad data in those fields to see how Confluence handles it. 
- Thanks for the heads up, I will be sure to include a flag for it
- Will do!

**Comment by jdknight** [comment]
Since this issue is a general inquiry and has been inactive for a couple of months, I will be marking this a closed. If any future prospect work related to JIRA directives want to be submitted to this extension, it can be done so through a pull request.
