### ISSUE TITLE
Travis CI is broken

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#17]
build is currently broken, should be updated with an atomic PR.

IF a particular python version is failing, it should be added to the allowed_failures matrix.

**Comment by jdknight** [comment]
Changes introduced in the [devwork-moving-pineapple](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/commits/devwork-moving-pineapple) branch appear to resolve this issue (see [build 220851046](https://travis-ci.org/tonybaloney/sphinxcontrib-confluencebuilder/builds/220851046)).

Will leave this issue opened until `devwork-moving-pineapple` is merged into the `master` (to ensure if any other changes do not break the Travis CI build).

**Comment by tonybaloney** [comment]
the master branch is now protected. https://help.github.com/articles/about-protected-branches/ just to stop accidentally pushing to master. everything has to go via PR and it has to pass the build first.

**Comment by tonybaloney** [comment]
Build is now fixed.
