### ISSUE TITLE
Confluence Cloud Support

### ISSUE THREAD

**Issue by lumpenpancho** [tonybaloney/sphinxcontrib-confluencebuilder#19]
Hello,

I am looking forward to this. Now completely through the setup I stumbled across the fact that the confluence remote API needs to be active. To confirm, you are talking about the REST API, and not the deprecated XML-RPC & SOAP API? 

Please clarify.

Thank you

Julian

**Comment by jdknight** [comment]
@lumpenpancho, if you're referring to "support rest api" #16, then yes; you will soon have the ability to use the REST API using this plugin (see [0.6 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/1)).

I've confirmed that using some changes from [devwork-moving-pineapple](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/tree/devwork-moving-pineapple) and pending changes to be pushed up soon, you _should_ be able to:
- Use this plugin to publish content to a Confluence Server v5.5+ instance using REST.
- Use this plugin to publish content to a Confluence Server v4.0+ instance using XML-RPC with Remote API enabled (until Confluence drops support).
- **Use this plugin to publish content to a Confluence Cloud instance using REST.**
- Use this plugin to publish content to a Confluence Cloud instance using XML-RPC with Remote API enabled (until Confluence drops support).

While you will be able to publish content to these variety of Confluence instances, you will still be limited to the [supported list of meta types](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder#supported-meta-types) (until additional types can be worked on).

**Comment by lumpenpancho** [comment]
Great explanation, thank you.

**Comment by jdknight** [comment]
REST API support can be followed in "support rest api" #16. Marking this issue as closed.
