### ISSUE TITLE
Add the package to the sphinx website

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#24]
http://www.sphinx-doc.org/en/stable/ext/thirdparty.html

We should be in one of the listings

**Comment by jdknight** [comment]
Merge requests have been pulled in:

- README.rst: add confluencebuilder [8e295053a27d](https://bitbucket.org/birkenfeld/sphinx-contrib/pull-requests/154)
- result-of-survey.tsv: add sphinxcontrib-confluencebuilder [e0c9b07bc93e](https://bitbucket.org/tk0miya/sphinxext_survey/pull-requests/3)

Site references should take effect next update cycle for documentation.
