### ISSUE TITLE
Write comparison with other projects out there

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#25]
Write a "how does this compare to xxx" on the readme. 

Look at https://github.com/Arello-Mobile/sphinx-confluence
And other modules matching similar ideas

**Comment by jdknight** [comment]
A comparison document is not planned at this time. I feel it is warranted that this issue can be marked as closed. If anyone see a benefit in making a comparison page and decides to introduce this information, it can be done so in a new pull request.
