### ISSUE TITLE
prepare a v0.7 release

### ISSUE THREAD

**Issue by jdknight** [tonybaloney/sphinxcontrib-confluencebuilder#29]
_Note: No expected release date planned at this time._

The following issue captures the overall intent to release v0.7 of the `sphinxcontrib-confluencebuilder` module. This includes issues and more found under [0.7 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/2).

Before this release is made, the following tests are desired to be performed:

Owner/Contributor Todos:
- [x] Ensure all issues and pull requests in [0.7 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/2) have been addressed.
- [x] (optional) Ensure [pluto-silly](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/commits/pluto-silly) branch is merged in (whenever desired).
- [x] (optional) Merge [brave-backpack](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/commits/brave-backpack) branch.
- [x] (optional) Merge [feature/readme-demo](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/tree/feature/readme-demo) branch.

Owner Todos:
- [x] Update `CHANGES.rst`, replacing `master` with release version and date.
- [x] Bumpversion to `release` (with tag).
- [x] Bumpversion to `minor`.
- [x] Push release cycle commits and tag to `origin/master`.
- [x] Update Read the Docs space.

Owner/Contributor Todos:
- [x] From release tag, build and publish to PyPI (using `twine`).
- [x] Close this issue.

**Comment by jdknight** [comment]
@tonybaloney, any interest in doing a v0.7 release? I'm hoping to take advantage of some of the changes/fixed introduced recently.

**Comment by tonybaloney** [comment]
yeah, totally, there are some lint and build errors though in #31 @jdknight

**Comment by jdknight** [comment]
@tonybaloney, thanks for recent reviews/merges. I've just re-tested a series of checks on Confluence Cloud and Confluence Server, and I believe it's a good time for a 0.7 release.

So, if you're willing and have the time, mind performing the release steps on the `master` branch? While you can also update PyPI as well, I'm also willing to performing the publishing (if you're busy).

**Comment by tonybaloney** [comment]
@jdknight all done and published

**Comment by jdknight** [comment]
@tonybaloney, awesome! Thanks!
