### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by dmc7337** [tonybaloney/sphinxcontrib-confluencebuilder#32]
Running to a confluence 6.2.1 site I got the TypeError that the JSO returned was bytes and not a string.
I fixed it by making the following change in rest.py wherever this code was used:
        try:
            # TODO Change this as does not decode binary response correctly
            # json_data = json.loads(rsp.content)
            json_data = rsp.json()
        except ValueError:
            raise ConfluenceBadServerUrlError(self.url,
                "REST reply did not provide valid JSON data.")

**Comment by jdknight** [comment]
I believe this issue has been resolved in d39cc84c82aee385310fc838c5da6a2f97044a6f (which is currently only on the head at the moment; planned for v0.7).

I'm trying trying to resolve an issue with setuptools/Travis CI; which may be resolved with a future (and unplanned) pip 9.0.2 release (https://github.com/pypa/pip/issues/4216).

**Comment by jdknight** [comment]
Assuming this issue is the same as d39cc84c82aee385310fc838c5da6a2f97044a6f , which has been merged in to the `master` (#31). Will be available in a v0.7 release; marking as closed. Feel free to re-open if needed.
