### ISSUE TITLE
Order of uploaded documents

### ISSUE THREAD

**Issue by oz123** [tonybaloney/sphinxcontrib-confluencebuilder#4]
@tonybaloney , first let me tell you how awesome I find this project! It is a bless, and I am willing to spend time and help.

Second, I have a project which is organized in the following way:
```
index.rst
    |------ background
    |------ software architecture
    ....
    ....
    ....
    |---- more modules.
```

The latex and html builders get the order correctly. However, when building this project with the confluence builder I get a list of text files, with no order, and when uploading the files to confluence the order is simply alphabetical traversing, which breaks the logical order, here is an example output:

```
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
Uploading page to confluence - Title "Aggregator"                                                                                                                                                          
Uploading page to confluence - Title "Software Architecture"                                                                                                                                               
Uploading page to confluence - Title "Background"                                                                                                                                                          
Uploading page to confluence - Title "BCM Gateway"                                                                                                                                                         
Uploading page to confluence - Title "Charger Gateway"                                                                                                                                                     
Uploading page to confluence - Title "Deployment"                                                                                                                                                          
Uploading page to confluence - Title "Glossary"                                                                                                                                                            
Uploading page to confluence - Title "Index"                                                                                                                                                     
Uploading page to confluence - Title "Logical view"                                                                                                                                                        
Uploading page to confluence - Title "Measurement Gateway"                                                                                                                                                 
Uploading page to confluence - Title "Operations"                                                                                                                                                          
Uploading page to confluence - Title "Performance"                                                                                                                                                         
Uploading page to confluence - Title "Process view"                                                                                                                                                        
Uploading page to confluence - Title "Software Quality"                                                                                                                                                    
Uploading page to confluence - Title "State Machine"                                                                                                                                                       
Uploading page to confluence - Title "Testing"                                                                                                                                                             
Uploading page to confluence - Title "Use Cases"                                                                                                                                                           
build succeeded, 4 warnings.
```

I could not find a way to control the order. Can this builder easily modified such that it keeps the order a la HTML or Latex builder?

**Comment by tonybaloney** [comment]
I haven't forgotten about this! it's just a bit tricky. I'll have a think

**Comment by jdknight** [comment]
I don't see a graceful way to support this. While Confluence does support an individual to [manually adjust the sequential ordering](https://confluence.atlassian.com/conf51/changing-the-sequential-order-of-pages-336169197.html), there appears to be no support in the [REST API](https://docs.atlassian.com/atlassian-confluence/REST/latest-server/#content-update) (and I assume legacy API capabilities; also see [CRA-1276](https://jira.atlassian.com/browse/CRA-1276)).

A very crude way would have this builder enforce order would be to detect and generate its own order via injected characters, but I don't think that would be proper or good for long time use.

There's two (2) workarounds that can be used:
1.  Publish your documentation and manually sort (`Move -> Reorder`) the slew of pages. While this is tedious, future publish attempts only update the page content, so your existing ordering is preserved.
2. Inject characters into your documentation so the generated output would be naturally ordered by Confluence. This is even less ideal since you are adding dummy characters which are seen in your Confluence pages and generated HTML/LaTeX documents.

I'm going to suggest we close this bug until Confluence's REST API supports the move/reorder capability (unless anyone else has a suggestion).

**Comment by jdknight** [comment]
Since Confluence does not provide an API method to control the ordering of page content, I'm going to close this issue.

If Confluence provides a means to order page content using their API, anyone is free to re-open this issue.

**Comment by jessetan** [comment]
The (deprecated) XML-RPC API actually has a method for this:

`void movePage(String token, String sourcePageId, String targetPageId, String position)` - moves a page's position in the hierarchy.

- sourcePageId - the id of the page to be moved.
- targetPageId - the id of the page that is relative to the sourcePageId page being moved.
- position - "above", "below", or "append". (Note that the terms 'above' and 'below' refer to the relative vertical position of the pages in the page tree.)

(From https://developer.atlassian.com/server/confluence/remote-confluence-methods/)

Unfortunately there is no equivalent function in the REST API: https://jira.atlassian.com/browse/CONFSERVER-40101
