### ISSUE TITLE
Add a way to publish without notifications.

### ISSUE THREAD

**Issue by sabinlinden** [tonybaloney/sphinxcontrib-confluencebuilder#42]
Normally when you publish a doc on Confluence, there is a checkbox next to the publish button that lets you choose whether or not to notify followers that the document has been published or updated. As far as I can tell, there is no documented way to select or unselect this option through confluencebuilder. Add this!

**Comment by jdknight** [comment]
This looks achievable. A comment in [CONFSERVER-38804](https://jira.atlassian.com/browse/CONFSERVER-38804?focusedCommentId=1555704&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1555704) indicates that supplying `message` and `minorEdit` in a REST update request would prevent notification. It should be possible to add a configuration option to toggle if a publish event results in a notification. For future reference, the REST update request is in [publisher.py](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/45061fd6a95be7981acb328201460826023a4fa7/sphinxcontrib/confluencebuilder/publisher.py#L302-L304).

As for supporting the legacy XML RPC API, I assume the same notification could be hidden via configuring `minorEdit` and `versionComment` in an [PageUpdateOptions](https://developer.atlassian.com/confdev/deprecated-apis/confluence-xml-rpc-and-soap-apis/remote-confluence-data-objects#RemoteConfluenceDataObjects-pageupdateoptionsPageUpdateOptions) object. The current code in [publisher.py](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/45061fd6a95be7981acb328201460826023a4fa7/sphinxcontrib/confluencebuilder/publisher.py#L324) only uses the `storePage` method at this time (which can create or update a page). Some logic would need to be added to use `storePage` for new pages and `updatePage` for existing pages (and then passing a properly configured `PageUpdateOptions` object).

**Comment by jdknight** [comment]
Pull request made in #46.

**Comment by jdknight** [comment]
This feature has been added to `master` and will be generally available for v0.7+ release. Marking as closed.
