### ISSUE TITLE
Python 3 json.loads requires str, not bytes

### ISSUE THREAD

**Issue by kylekeppler** [tonybaloney/sphinxcontrib-confluencebuilder#44]
In Python 3, `request.context` is `bytes`.  `request.text` is unicode `string` and can be passed to `json.loads`.

**Comment by jdknight** [comment]
@kylekeppler, I assume you're experiencing an issue that is fixed pending next release (see #32)?

**Comment by Siratm** [comment]
Hi all, actually rsp.text does not work correctly in python2.7.5. json.loads works but unicode are wrongly decoded (for instance if you have ' in your text you get strange characters in confluence).
Best regards.

**Comment by jdknight** [comment]
@Siratm, just for clarification, are you indicating there's an issue with using `rsp.text` and `json.loads`? From what I see in documentation, [rsp.txt](http://www.python-requests.org/en/latest/api/#requests.Response.text) should only be Unicode and [json.loads](https://docs.python.org/2.7/library/json.html#json.load) should only be accepting Unicode.

> ... but unicodes are wrongly decoded (for instance if you have ' in your text you get strange characters in confluence).

From this comment, I'm assuming you have experienced issues with some characters during the REST calls. I suspect that the root of the issue relates to #39 (improper markup handling). If this is not the case, you mind providing an example of the exact issue you're experiencing?

**Comment by jdknight** [comment]
@Siratm, I noticed the issue you've mentioned. I'll update #52 with information specific to the encoding errors.

As for this original issue, I'm assuming this is what was covered in #32. Marking as closed.

**Comment by Siratm** [comment]
Perfect thank you.

**Comment by kylekeppler** [comment]
@jdknight Yep, looks like #32 is the same issue.
