### ISSUE TITLE
 unexpected "garbage characters" with quotation mark | â€™

### ISSUE THREAD

**Issue by jdknight** [tonybaloney/sphinxcontrib-confluencebuilder#52]
In some cases, published Confluence pages may display undesired "garbage characters" inside documents. This is repeatable with a document such as:
````
:orphan:

oddity
======

Let's see this issue.
````
Where the rendered page would have the line:

> Letâ€™s see this issue.

This was a result of our received REST JSON data was interpreted from the Confluence instance. The response headers do not explicitly indicate that the received content-type is `application/json; charset=utf-8`; instead, just `application/json`. To address this issue, a fix will be made to interpret all received JSON data from Confluence to be UTF-8. This should be fine in most cases since [RFC-4627](https://www.ietf.org/rfc/rfc4627.txt) dictates that `application/json`shall be UTF-based (and by default UTF-8) and Atlassian documents that [Confluence should always be UTF-8](https://confluence.atlassian.com/doc/configuring-character-encoding-174010.html).

**Comment by jdknight** [comment]
I've added a commit fa206b18982ad7765fd23e57b47718c6795df5ac ("rest: interpret received data as utf-8"), pending to be a pull request. This should address issues with encoding. Since this is more of an informative issue, I'm going to preemptively mark it as closed. If anyone has addition comments or other concerns, feel free to make a comment.

**Comment by jdknight** [comment]
err -- re-opening until fa206b18982ad7765fd23e57b47718c6795df5ac is merged into `master`.

**Comment by tonybaloney** [comment]
@jdknight #53 is merged so I assume this issue is now resolved?

**Comment by jdknight** [comment]
@tonybaloney Yup!

This issue should now be resolved in db5b916e57898eb86244b4c33a801f5da5c3b984 (available on the master). To take advantage of this change, one can pull from `master`. This change should be made available in an upcoming v0.7 release (#29).
