### ISSUE TITLE
Create better documentation on PyPi

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#57]
The package summary on PyPi is too vague and minimal, recommend that one of the rST pages be included in setup.py instead.

**Comment by tonybaloney** [comment]
e.g. https://pypi.org/project/sphinxcontrib-confluencebuilder/

**Comment by marcinpraczko** [comment]
+1 for this - and descirbe all options / have more examples.

**Comment by tonybaloney** [comment]
The options are in https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html

The PyPi will just embed one of the existing rst pages.

**Comment by tonybaloney** [comment]
Done https://pypi.python.org/pypi/sphinxcontrib-confluencebuilder

**Comment by jdknight** [comment]
Looks nice. 🎉

**Comment by tonybaloney** [comment]
Looks slick in Warehouse too https://pypi.org/project/sphinxcontrib-confluencebuilder/

**Comment by marcinpraczko** [comment]
Looks really nice
