### ISSUE TITLE
How 'confluence_purge' option is working.

### ISSUE THREAD

**Issue by marcinpraczko** [tonybaloney/sphinxcontrib-confluencebuilder#59]
Hi, 

Can we describe all options in documentation, please?
Looking in code I see option 'confluence_purge' - however not sure how this is working.
I would like to avoid removing something which should be not removed ;).

This Issue is related with #57

**Comment by tonybaloney** [comment]
This is in the documentation https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html

**Comment by tonybaloney** [comment]
Resolved in #60

**Comment by marcinpraczko** [comment]
This documentation is really looking and thank you very much for addressing this.
