### ISSUE TITLE
Prepare a v0.8 release

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#61]
_Note: No expected release date planned at this time._

The following issue captures the overall intent to release v0.8 of the `sphinxcontrib-confluencebuilder` module. This includes issues and more found under [0.8 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/3).

Before this release is made, the following tests are desired to be performed:

Owner/Contributor Todos:
- [x] Ensure all issues and pull requests in [0.8 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/2) have been addressed.

Owner Todos:
- [x] Update `CHANGES.rst`, replacing `master` with release version and date.
- [x] Bumpversion to `release` (with tag).
- [x] Bumpversion to `minor`.
- [x] Push release cycle commits and tag to `origin/master`.
- [x] Update Read the Docs space.

Owner/Contributor Todos:
- [x] From release tag, build and publish to PyPI (using `twine`).
- [x] Close this issue.

**Comment by tonybaloney** [comment]
Published https://pypi.python.org/pypi/sphinxcontrib-confluencebuilder @jdknight

**Comment by marcinpraczko** [comment]
I know that this item is closed - I see info about bumpversion - I would recommend start using:
- https://github.com/peritus/bumpversion - can help a lot :)

**Comment by tonybaloney** [comment]
@marcinpraczko thanks! that's actually what we're using https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/master/setup.cfg#L1 :-) it's pretty cool
