### ISSUE TITLE
Possible to use with Confluence cloud?

### ISSUE THREAD

**Issue by petebachant** [tonybaloney/sphinxcontrib-confluencebuilder#69]
My team and I are using Confluence cloud with two-factor authentication, and would like to push some Sphinx docs. Has this use case ever been tested?

**Comment by jdknight** [comment]
@petebachant, it's not supported at this time. Atlassian's documentation [indicates](https://confluence.atlassian.com/cloud/secure-your-account-with-two-step-verification-939505063.html):

> **API access tokens with two-step verification**
If you enable two-step verification on an account that is used by scripts or services to access Atlassian Cloud REST APIs, then that account won't be able to use a password for basic authentication against a REST API. We recommend that you use an API token instead, although an organization admin could exclude the relevant account from two-step verification. Read more about API tokens.

To use the REST API (as stated above), an API token will need to be used instead. Unfortunately, when I go to my Confluence Cloud instance, it states that "[API tokens are] not available just yet. We're working on it, so please try again in the future". When API tokens into either a more working beta state or completely supported, we'll make sure this capability is added.

**Comment by jdknight** [comment]
@petebachant, got some good news. The Atlassian cloud instance I have access now has the ability to create API tokens. After creating a token and testing with the most recent release of this extension, I'm happy to say that API tokens already work. By using your account's Email as the username (`confluence_server_user`) and API token value as the password (`confluence_server_pass`), you should be able to authenticate when using the REST API (note: API token support is not available over XML-RPC).

That all being said, I'll try to update our documentation to explicitly indicate this (and probably even promote to use API tokens over using an account's password).

Closing this issue (and thanks for bringing this up).

**Comment by petebachant** [comment]
Just getting back to this now. Thanks a lot for your help!
