### ISSUE TITLE
UnknownMacroMigrationException

### ISSUE THREAD

**Issue by jwesty** [tonybaloney/sphinxcontrib-confluencebuilder#75]
**Confluence: 6.4**
**Python 2.7.13 in virutalenv**

I've been digging, and digging, and digging, and can't seem to find the solution to my issue... maybe the community has seen it before. My configuration in conf.py is pretty basic, but I have tried with the purge option too just in case: 

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.httpdomain',
    'sphinxcontrib.autohttp.flask',
    'sphinxcontrib.autohttp.flaskqref',
    'sphinxcontrib.confluencebuilder'
]
```
```
confluence_publish = True
confluence_space_name = 'DE'
confluence_parent_page = 'API Documentation'
confluence_server_url = 'https://my.confluence.server.com/'
confluence_server_user = 'user'
confluence_server_pass = 'pass'
```

What I'm seeing is this error from running `make confluence` and I figured I'd just drop the full output in case I'm missing something simple: 

```
Running Sphinx v1.5.6
loading pickled environment... not yet created
loading intersphinx inventory from http://flask.pocoo.org/docs/objects.inv...
loading intersphinx inventory from http://docs.sqlalchemy.org/en/latest/objects.inv...
loading intersphinx inventory from http://werkzeug.pocoo.org/docs/objects.inv...
loading intersphinx inventory from https://marshmallow.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from http://flask-sqlalchemy.pocoo.org/objects.inv...
loading intersphinx inventory from http://geoalchemy-2.readthedocs.io/en/0.3/objects.inv...
loading intersphinx inventory from https://marshmallow-sqlalchemy.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [confluence]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
publishing... [100%] index
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: POST
RSP: 500
URL: https://my.confluence.server.com/rest/api/
API: contentbody/convert/storage
MSG: com.atlassian.confluence.content.render.xhtml.migration.exceptions.UnknownMacroMigrationException: The macro '   "data"' is unknown.
---

make: *** [confluence] Error 1
```

Digging in the publisher.py looks to be valid with what the Confluence API is looking for: 

```
raw_data_req = {
                'value': raw_data,
                'representation': 'wiki'
            }
```
https://docs.atlassian.com/atlassian-confluence/REST/6.5.2/#contentbody/convert/{to}

**Comment by marcinpraczko** [comment]
Hi, 

I suggest to double check proper URL, I saw similar issue when I missed `/wiki/` in my `conf.py`.
Could you try setup URL for: `https://my.confluence.server.com/wiki/` and check if this help?

**Comment by jdknight** [comment]
The error `UnknownMacroMigrationException` from Confluence should only happen when a macro definition is provided with an unknown macro type. A macro should be defined through the use of curly brackets (ex: `{mymacro}`). The error you've provided seems to be that a macro of type `   "data"` is being provided.

What I suspect is that somewhere in your documentation, you might have a JSON-like content which may be leading with:
```
{
    "data": ...
```
What's odd is that the current stable release (v0.8) of this extension should ensure the curly bracket values are escaped ([ref](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/v0.8/sphinxcontrib/confluencebuilder/translator/wiki.py#L29-L30); see also PR #72 for related upcoming escaping fixing). I'm wondering if the content is not always being escaped in your scenario.

I assume from the output, the issue resides inside the `index` document. Out of curiosity, if you inspect the generated output file (`index.conf`; which will be published to Confluence during the convert stage), do you have any curly brackets or see signs of the `"data"` text in your document?

**Comment by jwesty** [comment]
Sorry for the delay here guys! I appreciate the responses and I'll let you know what I find out (hopefully tomorrow).

**Comment by jwesty** [comment]
@jdknight Our sphix have tons of occurrences with the "data" attribute: 

```
.. sourcecode:: http

            HTTP/1.1 200 OK
            Content-Type: application/json

            {
              "data": [
                {
                  "value1": 1,
                  "value2": 2,
                  "conditional_value": .001
```

I will try removing "data" and replacing with something else and let you know the results!

**Comment by jdknight** [comment]
I've replicated a similar issue in a test environment using the following source in a document:
```
.. sourcecode:: {

    {
        "data": []
    }
```
Which gets converted to:
```
{code:linenumbers=false|language={}
{
    "data": []
}
{code}
```
That results in the following exception:
```
An unsupported Confluence API call has been made.

REQ: POST
RSP: 500
URL: <url>
API: contentbody/convert/storage
MSG: com.atlassian.confluence.content.render.xhtml.migration.exceptions.UnknownMacroMigrationException: The macro '    "data"' is unknown.
```

I'm curious, do you have any `.. sourcecode::` markup which you provide an odd language value?

----

On a side note, I see your example has a `http` language type, which will most likely fail for the current implementation of this extension. Internally, there should be a check which translates an unsupported language value to just the `none` language type (so code at least renders in plain text). I'll make a note of this to address in the future.

**Comment by jwesty** [comment]
`.. sourcecode:: none` Didn't render very well, which I wouldn't expect it to :)

**Comment by jdknight** [comment]
@jwesty, yup ~ Confluence provides only a limited subset of syntax highlighting support ([server](https://confluence.atlassian.com/doc/code-block-macro-139390.html), [cloud](https://confluence.atlassian.com/confcloud/code-block-macro-724765175.html)).

Thanks for bringing up the issues you had in your scenario. There's definitively tweaks/changes we can do to this extension to limit some issues you've experienced.  I like to leave this issue is opened so I can try an apply the issue you've mentioned above ([comment-357289379](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/issues/75#issuecomment-357289379)) and see if there is a way to mitigate it from occurring for other users.

Also (for my future reference), I hope to create a issue to adjust code macro language to use only supported Confluence markup defined. It may be beneficial to add advanced options to allow a user to either force all language types to `none` (to help force non-highlighting if there is a highlight issue) or allow the language value to be permitted (to allow bypass for new-and-official syntax highlighting or even third-party extension highlight (if that even exists)).

**Comment by jwesty** [comment]
Appreciate the collaboration here!
