### ISSUE TITLE
Embed images on Cofluence page

### ISSUE THREAD

**Issue by brxie** [tonybaloney/sphinxcontrib-confluencebuilder#94]
Hi there,

Thanks for making awesome extension!
Could you please let me know, is it in plans to make support for uploading images to Cofluence?
Didn't see it on Supported Markup list.

Regards,
brxie

**Comment by akall80** [comment]
Hello, 
I quote @brxie: wonderful extension, seamlessly working.
Missing images linking and uploading. Do you have any plan?

Many thanks and regards,
A

**Comment by jdknight** [comment]
Unless someone else attempts to provide such a contribution, here's the order of things to which I'll have the opportunity to possibly start image markup support:

1. First, the slew of pending pull requests need to be reviewed and possible accepted (when @tonybaloney has the time; unknown duration).
2. Once the pull requests have been assessed, I have a series of Confluence validation tests changes I'd like to submit and verify existing markup. Ideally from this, generate a new stable version (approximately 1-2 weeks plus release review time).
3. Address the feature request outlined in issue #51 (approximately 1 week to a month).

Once these are addressed, I don't mind attempting to support image markup.

**Comment by jdknight** [comment]
I am going to close this issue in favour of issue #131 (where progress updates on image support will be updated).
