### ISSUE TITLE
prepare release v0.9

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#95]
The following issue captures the overall intent to release v0.9 of the `sphinxcontrib-confluencebuilder` module. This includes issues and more found under [0.9 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/3).

Before this release is made, the following items are desired to be performed:

Owner/Contributor Todos:
- [x] Finalize and submit the new (pending) tests for markup validation (@jdknight):
- Perform validation tests using the following Confluence variants:
   - REST API Publishing and Purging
     - [x] Confluence Cloud
     - [x] Confluence Server 5.9
     - [x] Confluence Server 5.10.8
     - [x] Confluence Server 6.0.7
     - [x] Confluence Server 6.1.4
     - [x] Confluence Server 6.2.4
     - [x] Confluence Server 6.3.4
     - [x] Confluence Server 6.4.3
     - [x] Confluence Server 6.5.2
     - [x] Confluence Server 6.6.3
     - [x] Confluence Server 6.7.1
   - XML-RPC Publishing and Purging
     - [x] Confluence Cloud
     - [x] Confluence Server 5.9
     - [x] Confluence Server 5.10.8
     - [x] Confluence Server 6.0.7
     - [x] Confluence Server 6.1.4
     - [x] Confluence Server 6.2.4
     - [x] Confluence Server 6.3.4
     - [x] Confluence Server 6.4.3
     - [x] Confluence Server 6.5.2
     - [x] Confluence Server 6.6.3
     - [x] Confluence Server 6.7.1
- [x] Ensure `CHANGES.rst` is up-to-date (contained in #106).

Owner Todos:
- [x] Update `CHANGES.rst`, replacing `master` with release version and date.
- [x] Bumpversion to `release` (with tag).
- [x] Bumpversion to `minor`.
- [x] Push release cycle commits and tag to `origin/master`.
- [x] Update Read the Docs space.

Owner/Contributor Todos:
- [x] From release tag, build and publish to PyPI (using `twine`).
- [x] Close this issue.
- [ ] Merge any pending/reviewed changes from `next` into `master`.

**Comment by jdknight** [comment]
@tonybaloney, if you approve of the changes introduced in #106 (I can make changes on this review if desired), I'm happy if you want to proceed with a release.

**Comment by loganasherjones** [comment]
Any chance we can get this released?

**Comment by tonybaloney** [comment]
Released on PyPi
